# Generated by Django 3.1.7 on 2021-02-22 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeatBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=64)),
                ('person_name', models.CharField(max_length=200)),
                ('seat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seat_booking.seat')),
            ],
        ),
    ]
