# Generated by Django 3.1.7 on 2021-02-22 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seat_booking', '0002_auto_20210222_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='seatbooking',
            name='seat_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seat_booking.seat'),
        ),
    ]
